apiVersion: v1
kind: Namespace
metadata:
  name: signalboard
---
apiVersion: v1
kind: Secret
metadata:
  name: signalboard-db-secret
  namespace: signalboard
type: Opaque
stringData:
  POSTGRES_USER: signalboard_user
  POSTGRES_PASSWORD: change-me-via-sealed-secrets-in-real-use
  POSTGRES_DB: signalboard_db
