apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: signalboard
resources:
  - ../../base
patchesStrategicMerge:
  - db-pool-patch.yaml
images:
  - name: ghcr.io/devesh537/signalboard-backend
    newTag: latest
  - name: ghcr.io/devesh537/signalboard-frontend
    newTag: latest
